# __NLP Natural Language Process__

In [7]:
import pandas as pd
import re
import string

In [4]:
df = pd.read_csv("movie_reviews.csv", delimiter="\t")
df.head()

                   review sentiment
0  This movie was amazing  Positive
1     I loved every scene  Positive
2        Fantastic acting  Positive
3         Best movie ever  Positive
4         Wonderful story  Positive

## __Text Cleaning__

In [5]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'https?://\S+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = text.encode('ascii', 'ignore').decode('ascii')
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [10]:
df['clean_review'] = df['review'].apply(clean_text)
df[['review', 'clean_review']].head()

                   review            clean_review
0  This movie was amazing  this movie was amazing
1     I loved every scene     i loved every scene
2        Fantastic acting        fantastic acting
3         Best movie ever         best movie ever
4         Wonderful story         wonderful story

## __Tokenization__

In [11]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [14]:
df['token'] = df['clean_review'].apply(word_tokenize)

In [15]:
df['token_count'] = df['token'].apply((len))

In [16]:
df.head()

,review,sentiment,clean_review,token,token_count
0,This movie was amazing,Positive,this movie was amazing,"[this, movie, was, amazing]",4
1,I loved every scene,Positive,i loved every scene,"[i, loved, every, scene]",4
2,Fantastic acting,Positive,fantastic acting,"[fantastic, acting]",2
3,Best movie ever,Positive,best movie ever,"[best, movie, ever]",3
4,Wonderful story,Positive,wonderful story,"[wonderful, story]",2

## __Stop Words Removing__

In [18]:
from nltk.corpus import stopwords
from string import punctuation

In [19]:
stop = stopwords.words("english")

In [20]:
stop_words = list(punctuation) + stop

In [22]:
df['filtered_token'] = df['token'].apply(
    lambda token: [word for word in token if word not in stop_words]
)

In [23]:
df.head()

,review,sentiment,clean_review,token,token_count,filtered_token
0,This movie was amazing,Positive,this movie was amazing,"[this, movie, was, amazing]",4,"[movie, amazing]"
1,I loved every scene,Positive,i loved every scene,"[i, loved, every, scene]",4,"[loved, every, scene]"
2,Fantastic acting,Positive,fantastic acting,"[fantastic, acting]",2,"[fantastic, acting]"
3,Best movie ever,Positive,best movie ever,"[best, movie, ever]",3,"[best, movie, ever]"
4,Wonderful story,Positive,wonderful story,"[wonderful, story]",2,"[wonderful, story]"

In [24]:
custom_stop_words = set(stopwords.words("english"))

custom_stop_words.discard("not")
custom_stop_words.discard("no")
custom_stop_words.discard("never")

In [25]:
df['filtered_token'] = df['token'].apply(
    lambda token: [word for word in token if word not in custom_stop_words]
)

In [26]:
df.head()

,review,sentiment,clean_review,token,token_count,filtered_token
0,This movie was amazing,Positive,this movie was amazing,"[this, movie, was, amazing]",4,"[movie, amazing]"
1,I loved every scene,Positive,i loved every scene,"[i, loved, every, scene]",4,"[loved, every, scene]"
2,Fantastic acting,Positive,fantastic acting,"[fantastic, acting]",2,"[fantastic, acting]"
3,Best movie ever,Positive,best movie ever,"[best, movie, ever]",3,"[best, movie, ever]"
4,Wonderful story,Positive,wonderful story,"[wonderful, story]",2,"[wonderful, story]"

## __Stemming & Lemmatization__

In [27]:
from nltk.stem import PorterStemmer, WordNetLemmatizer

In [28]:
stem = PorterStemmer()
lema = WordNetLemmatizer()

### Stemming

In [29]:
df['stemmed_token'] = df['filtered_token'].apply(
    lambda token: [stem.stem(word) for word in token]
)

### Lemmatization

In [30]:
df['lematize_token'] = df['filtered_token'].apply(
    lambda token: [lema.lemmatize(word, pos='v') for word in token]
)

In [31]:
df.head()

,review,sentiment,clean_review,token,token_count,filtered_token,stemmed_token,lematize_token
0,This movie was amazing,Positive,this movie was amazing,"[this, movie, was, amazing]",4,"[movie, amazing]","[movi, amaz]","[movie, amaze]"
1,I loved every scene,Positive,i loved every scene,"[i, loved, every, scene]",4,"[loved, every, scene]","[love, everi, scene]","[love, every, scene]"
2,Fantastic acting,Positive,fantastic acting,"[fantastic, acting]",2,"[fantastic, acting]","[fantast, act]","[fantastic, act]"
3,Best movie ever,Positive,best movie ever,"[best, movie, ever]",3,"[best, movie, ever]","[best, movi, ever]","[best, movie, ever]"
4,Wonderful story,Positive,wonderful story,"[wonderful, story]",2,"[wonderful, story]","[wonder, stori]","[wonderful, story]"

In [32]:
df['processed_token'] = df['lematize_token'].apply(
    lambda token: " ".join(token)
)

df.head()

,review,sentiment,clean_review,token,token_count,filtered_token,stemmed_token,lematize_token,processed_token
0,This movie was amazing,Positive,this movie was amazing,"[this, movie, was, amazing]",4,"[movie, amazing]","[movi, amaz]","[movie, amaze]",movie amaze
1,I loved every scene,Positive,i loved every scene,"[i, loved, every, scene]",4,"[loved, every, scene]","[love, everi, scene]","[love, every, scene]",love every scene
2,Fantastic acting,Positive,fantastic acting,"[fantastic, acting]",2,"[fantastic, acting]","[fantast, act]","[fantastic, act]",fantastic act
3,Best movie ever,Positive,best movie ever,"[best, movie, ever]",3,"[best, movie, ever]","[best, movi, ever]","[best, movie, ever]",best movie ever
4,Wonderful story,Positive,wonderful story,"[wonderful, story]",2,"[wonderful, story]","[wonder, stori]","[wonderful, story]",wonderful story

In [33]:
df.to_csv("processed.csv", index=False)

## __Preprocessing is Complete__

# __Model Feeding Techniques in NLP__

Machine learning models cannot directly understand raw text. Before feeding text into a model, we must convert words or sentences into numerical features.

This conversion process is called **text vectorization** or **feature extraction**.

Common model feeding techniques are:

1. Bag of Words / BoW
2. N-grams
3. TF-IDF
4. Count Vectorization
5. TF-IDF Vectorization
6. Word Embeddings
7. Sentence Embeddings

## __1. Bag of Words / BoW__

**Bag of Words** converts text into numbers by counting how many times each word appears in a document.

It ignores grammar and word order. It only checks word frequency.

Example:

| Text | Feature Output |
|---|---|
| `movie good good` | `movie=1, good=2` |
| `movie bad` | `movie=1, bad=1` |

Importing:

```python
from sklearn.feature_extraction.text import CountVectorizer
```

Syntax:

```python
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['processed_token'])
```

To see feature names:

```python
vectorizer.get_feature_names_out()
```

To convert sparse matrix into DataFrame:

```python
bow_df = pd.DataFrame(
    X.toarray(),
    columns=vectorizer.get_feature_names_out()
)
```

When to use BoW:

- Simple text classification
- Small datasets
- Baseline NLP models
- Sentiment analysis basics

Limitation:

- It ignores word meaning and word order.
- Common words may get high importance even if they are not useful.

## __2. N-grams__

**N-grams** are continuous combinations of `n` words from text.

| Type | Meaning | Example |
|---|---|---|
| Unigram | 1 word | `good` |
| Bigram | 2 words | `good movie` |
| Trigram | 3 words | `very good movie` |

N-grams help preserve some word order and context.

Importing:

```python
from sklearn.feature_extraction.text import CountVectorizer
```

Syntax for unigram + bigram:

```python
vectorizer = CountVectorizer(ngram_range=(1, 2))
X = vectorizer.fit_transform(df['processed_token'])
```

Syntax for only bigrams:

```python
vectorizer = CountVectorizer(ngram_range=(2, 2))
X = vectorizer.fit_transform(df['processed_token'])
```

Syntax for unigram + bigram + trigram:

```python
vectorizer = CountVectorizer(ngram_range=(1, 3))
X = vectorizer.fit_transform(df['processed_token'])
```

When to use N-grams:

- When word combinations are important
- Sentiment analysis
- Spam detection
- Text classification

Example: `not good` and `good` have very different meanings. Bigram features can capture `not good` as one feature.

## __3. TF-IDF__

**TF-IDF** means **Term Frequency - Inverse Document Frequency**.

It gives importance to words based on two ideas:

| Part | Meaning |
|---|---|
| TF | How often a word appears in one document |
| IDF | How rare or important the word is across all documents |

Words that appear frequently in one document but not in every document get higher importance.

Importing:

```python
from sklearn.feature_extraction.text import TfidfVectorizer
```

Syntax:

```python
tfidf = TfidfVectorizer()
X = tfidf.fit_transform(df['processed_token'])
```

To see TF-IDF feature names:

```python
tfidf.get_feature_names_out()
```

To convert into DataFrame:

```python
tfidf_df = pd.DataFrame(
    X.toarray(),
    columns=tfidf.get_feature_names_out()
)
```

TF-IDF with N-grams:

```python
tfidf = TfidfVectorizer(ngram_range=(1, 2))
X = tfidf.fit_transform(df['processed_token'])
```

When to use TF-IDF:

- Text classification
- Sentiment analysis
- Search engines
- Document similarity
- Spam detection

Advantage:

- Better than simple BoW because it reduces the importance of very common words.

Limitation:

- It still does not understand true word meaning like modern embeddings do.

## __4. Vectorization__

**Vectorization** means converting text into numerical vectors so that ML models can understand it.

In NLP, vectorization can be done using:

| Vectorization Method | Importing | Syntax | Output |
|---|---|---|---|
| Count Vectorization / BoW | `from sklearn.feature_extraction.text import CountVectorizer` | `CountVectorizer()` | Word count features |
| Count Vectorization with N-grams | `from sklearn.feature_extraction.text import CountVectorizer` | `CountVectorizer(ngram_range=(1, 2))` | Word and phrase count features |
| TF-IDF Vectorization | `from sklearn.feature_extraction.text import TfidfVectorizer` | `TfidfVectorizer()` | Weighted word importance features |
| TF-IDF with N-grams | `from sklearn.feature_extraction.text import TfidfVectorizer` | `TfidfVectorizer(ngram_range=(1, 2))` | Weighted word and phrase features |

General syntax:

```python
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

vectorizer = CountVectorizer()
# or
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df['processed_token'])
```

Important methods:

| Method | Use |
|---|---|
| `fit()` | Learns vocabulary from text |
| `transform()` | Converts text into numeric form using learned vocabulary |
| `fit_transform()` | Learns vocabulary and converts text at the same time |
| `get_feature_names_out()` | Shows created feature names |
| `toarray()` | Converts sparse matrix into normal array |

Example for training a model after vectorization:

```python
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X = vectorizer.fit_transform(df['processed_token'])
y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
```

## __5. Word Embeddings__

**Word embeddings** convert words into dense numerical vectors that can capture meaning and similarity.

Unlike BoW and TF-IDF, embeddings can understand that similar words may have related meanings.

| Technique | Meaning |
|---|---|
| Word2Vec | Learns word vectors based on nearby words |
| GloVe | Learns word vectors using global word co-occurrence statistics |
| FastText | Similar to Word2Vec but also uses sub-word information |
| Transformer Embeddings | Uses deep learning models like BERT to create contextual vectors |

Example using Word2Vec:

```python
from gensim.models import Word2Vec

model = Word2Vec(
    sentences=df['filtered_token'],
    vector_size=100,
    window=5,
    min_count=1
)

word_vector = model.wv['movie']
```

When to use word embeddings:

- When meaning of words is important
- Larger NLP projects
- Deep learning models
- Similarity-based tasks

## __Quick Summary__

| Technique | What It Does | Best For |
|---|---|---|
| BoW | Counts word frequency | Simple baseline models |
| N-grams | Counts word combinations | Capturing short context |
| TF-IDF | Gives weight based on word importance | Text classification and search |
| Count Vectorization | Converts text into count vectors | Classical ML models |
| TF-IDF Vectorization | Converts text into weighted vectors | Better classical ML performance |
| Word Embeddings | Converts words into meaning-based dense vectors | Semantic NLP tasks |

Final flow:

```python
Raw Text -> Cleaning -> Tokenization -> Stop Word Removal -> Stemming/Lemmatization -> Vectorization -> Model Training
```