# __Assignment 14 Part 1 to 4__

## Task 1 to 7

## __Task 1__

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Cleaned_Tatanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S

In [3]:
print("Columns :")
print(df.columns)
print("\nMissing Values :")
print(df.isnull().sum())

Columns :
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

Missing Values :
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

## __Task 1__

In [4]:
df['Family_size'] = df['SibSp'] + df['Parch'] + 1

df[['SibSp','Parch','Family_size']].head()

   SibSp  Parch  Family_size
0      0      0            1
1      1      0            2
2      0      0            1
3      0      0            1
4      1      1            3

In [5]:
df['Fare_per_person'] = df['Fare'] / df['Family_size']

df[['Fare', 'Family_size', 'Fare_per_person']].head()

      Fare  Family_size  Fare_per_person
0   7.8292            1         7.829200
1   7.0000            2         3.500000
2   9.6875            1         9.687500
3   8.6625            1         8.662500
4  12.2875            3         4.095833

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Family_size,Fare_per_person
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q,1,7.829200
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S,2,3.500000
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q,1,9.687500
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S,1,8.662500
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S,3,4.095833

## __Task 2__

This Dataset doesn't have Date Column so skipping it

In [7]:
df['Word_count'] = df['Name'].str.split().str.len()
df['Text_len'] = df['Name'].str.replace(" ", "").str.len()

df[['Word_count','Text_len']].head()

   Word_count  Text_len
0           3        14
1           5        28
2           4        22
3           3        14
4           6        39

## __Task 3__

In [8]:
embarked_dummies = pd.get_dummies(df["Embarked"], prefix="Embarked", dtype=int)
df = pd.concat([df, embarked_dummies], axis=1)

In [9]:
df[["Embarked", "Embarked_C", "Embarked_Q", "Embarked_S"]].head()

  Embarked  Embarked_C  Embarked_Q  Embarked_S
0        Q           0           1           0
1        S           0           0           1
2        Q           0           1           0
3        S           0           0           1
4        S           0           0           1

In [10]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Family_size,Fare_per_person,Word_count,Text_len,Embarked_C,Embarked_Q,Embarked_S
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q,1,7.829200,3,14,0,1,0
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S,2,3.500000,5,28,0,0,1
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q,1,9.687500,4,22,0,1,0
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S,1,8.662500,3,14,0,0,1
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S,3,4.095833,6,39,0,0,1

## __Task 4__

In [11]:
categorical_features = df[['Name','Sex','Embarked']]
numerical_features = df.drop(columns=['Name','Sex','Embarked'])

In [12]:
categorical_features.head()

                                           Name     Sex Embarked
0                              Kelly, Mr. James    male        Q
1              Wilkes, Mrs. James (Ellen Needs)  female        S
2                     Myles, Mr. Thomas Francis    male        Q
3                              Wirz, Mr. Albert    male        S
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female        S

In [13]:
numerical_features.head()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Ticket,Fare,Family_size,Fare_per_person,Word_count,Text_len,Embarked_C,Embarked_Q,Embarked_S
0,892,0,3,34.5,0,0,330911,7.8292,1,7.829200,3,14,0,1,0
1,893,1,3,47.0,1,0,363272,7.0000,2,3.500000,5,28,0,0,1
2,894,0,2,62.0,0,0,240276,9.6875,1,9.687500,4,22,0,1,0
3,895,0,3,27.0,0,0,315154,8.6625,1,8.662500,3,14,0,0,1
4,896,1,3,22.0,1,1,3101298,12.2875,3,4.095833,6,39,0,0,1

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [15]:
df['Sex'] =le.fit_transform(df['Sex'])

In [16]:
df['Embarked']=le.fit_transform(df['Embarked'])

In [17]:
df['Name'] = le.fit_transform(df['Name'])

In [18]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Family_size,Fare_per_person,Word_count,Text_len,Embarked_C,Embarked_Q,Embarked_S
0,892,0,3,206,1,34.5,0,0,330911,7.8292,1,1,7.829200,3,14,0,1,0
1,893,1,3,403,0,47.0,1,0,363272,7.0000,2,2,3.500000,5,28,0,0,1
2,894,0,2,269,1,62.0,0,0,240276,9.6875,1,1,9.687500,4,22,0,1,0
3,895,0,3,408,1,27.0,0,0,315154,8.6625,2,1,8.662500,3,14,0,0,1
4,896,1,3,178,0,22.0,1,1,3101298,12.2875,2,3,4.095833,6,39,0,0,1

## __Task 5__

In [19]:
from sklearn.preprocessing import StandardScaler , MinMaxScaler

std_scaler = StandardScaler()

In [28]:
df_scaled = df.copy()

In [29]:
df_scaled[['Age','Fare']] = std_scaler.fit_transform(df_scaled[['Age','Fare']])

In [30]:
print("New Means:\n", df_scaled[['Age','Fare']].mean().round(2))
print("\nNew Std Devs:\n", df_scaled[['Age','Fare']].std().round(2))

New Means:
 Age     0.0
Fare    0.0
dtype: float64

New Std Devs:
 Age     1.0
Fare    1.0
dtype: float64

In [31]:
df_scaled[['Age','Fare']].head()

        Age      Fare
0  0.386231 -0.497413
1  1.371370 -0.512278
2  2.553537 -0.464100
3 -0.204852 -0.482475
4 -0.598908 -0.417492

### Standard Scaler Formula ---> Z = (x - mu)/ sigma
__Mean__ : The formula subtracts the average value (mu) from every single data point. This process is called centering. By subtracting the center point from all values, the entire data distribution shifts so that its new balance point (the average) sits perfectly at 0.

__Standard Deviation__ : After centering the data, the formula divides every value by the original standard deviation (sigma). This process is called scaling. It compresses or expands the spread of the data points so that the average distance of all data points from the center (0) is exactly 1 unit.

## __Task 6__

In [34]:
minmax_scaler = MinMaxScaler(feature_range=(0, 1))

In [32]:
df_normalized = df.copy()

In [35]:
df_normalized[["Age","Fare"]] = minmax_scaler.fit_transform(df[['Age','Fare']])

In [36]:
df_normalized[['Age','Fare']].head()

        Age      Fare
0  0.452723  0.015282
1  0.617566  0.013663
2  0.815377  0.018909
3  0.353818  0.016908
4  0.287881  0.023984

In [37]:
print("Minimum Values (Should be 0):\n", df[['Age','Fare']].min())
print("\nMaximum Values (Should be 1):\n", df[['Age','Fare']].max())

Minimum Values (Should be 0):
 Age     0.17
Fare    0.00
dtype: float64

Maximum Values (Should be 1):
 Age      76.0000
Fare    512.3292
dtype: float64

In [40]:
print("Comparision of Standard Scaler vs MinMax Scaler")
print("\nStandard Scaler")
print(df_scaled[['Age','Fare']].head())
print("\nMinMax Scaler")
print(df_normalized[['Age','Fare']].head())

Comparision of Standard Scaler vs MinMax Scaler

Standard Scaler
        Age      Fare
0  0.386231 -0.497413
1  1.371370 -0.512278
2  2.553537 -0.464100
3 -0.204852 -0.482475
4 -0.598908 -0.417492

MinMax Scaler
        Age      Fare
0  0.452723  0.015282
1  0.617566  0.013663
2  0.815377  0.018909
3  0.353818  0.016908
4  0.287881  0.023984

## __Task 7__

In [41]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

In [43]:
num_pipeline = Pipeline([
    ("scalar", StandardScaler())
])

In [42]:
cate_pipeline = Pipeline([
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

In [44]:
preprocessor = ColumnTransformer(transformers=[
    ("num", num_pipeline, numerical_features),
    ("cat", cate_pipeline, categorical_features)
])

In [45]:
preprocessor

,"transformers transformers: list of tuplesList of (name, transformer, columns) tuples specifying thetransformer objects to be applied to subsets of the data.name : str Like in Pipeline and FeatureUnion, this allows the transformer and its parameters to be set using ``set_params`` and searched in grid search.transformer : {'drop', 'passthrough'} or estimator Estimator must support :term:`fit` and :term:`transform`. Special-cased strings 'drop' and 'passthrough' are accepted as well, to indicate to drop the columns or to pass them through untransformed, respectively.columns : str, array-like of str, int, array-like of int, array-like of bool, slice or callable Indexes the data on its second axis. Integers are interpreted as positional columns, while strings can reference DataFrame columns by name. A scalar string or int should be used where ``transformer`` expects X to be a 1d array-like (vector), otherwise a 2d array will be passed to the transformer. A callable is passed the input data `X` and can return any of the above. To select multiple columns by name or dtype, you can use :obj:`make_column_selector`.","[('num', ...), ('cat', ...)]"
,"remainder remainder: {'drop', 'passthrough'} or estimator, default='drop'By default, only the specified columns in `transformers` aretransformed and combined in the output, and the non-specifiedcolumns are dropped. (default of ``'drop'``).By specifying ``remainder='passthrough'``, all remaining columns thatwere not specified in `transformers`, but present in the data passedto `fit` will be automatically passed through. This subset of columnsis concatenated with the output of the transformers. For dataframes,extra columns not seen during `fit` will be excluded from the outputof `transform`.By setting ``remainder`` to be an estimator, the remainingnon-specified columns will use the ``remainder`` estimator. Theestimator must support :term:`fit` and :term:`transform`.Note that using this feature requires that the DataFrame columnsinput at :term:`fit` and :term:`transform` have identical order.",'drop'
,"sparse_threshold sparse_threshold: float, default=0.3If the output of the different transformers contains sparse matrices,these will be stacked as a sparse matrix if the overall density islower than this value. Use ``sparse_threshold=0`` to always returndense. When the transformed output consists of all dense data, thestacked result will be dense, and this keyword will be ignored.",0.3
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.",None
,"transformer_weights transformer_weights: dict, default=NoneMultiplicative weights for features per transformer. The output of thetransformer is multiplied by these weights. Keys are transformer names,values the weights.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each transformer will beprinted as it is completed.",False
,"verbose_feature_names_out verbose_feature_names_out: bool, str or Callable[[str, str], str], default=True- If True, :meth:`ColumnTransformer.get_feature_names_out` will prefix all feature names with the name of the transformer that generated that feature. It is equivalent to setting `verbose_feature_names_out=""{transformer_name}__{feature_name}""`.- If False, :meth:`ColumnTransformer.get_feature_names_out` will not prefix any feature names and will error if feature names are not unique.- If ``Callable[[str, str], str]``, :meth:`ColumnTransformer.get_feature_names_out` will rename all the features using the name of the transformer. The first argument of the callable is the transformer name and the second argument is the feature name. The returned string will be the new feature name.- If ``str``, it must be a string ready for formatting. The given string will be formatted using two field names: ``transformer_name`` and ``feature_name``. e.g. ``""{feature_name}__{transformer_name}""``. See :meth:`str.format` method from the standard library for more info... versionadded:: 1.0.. versionchanged:: 1.6 `verbose_feature_names_out` can be a callable or a string to be formatted.",True
,"copy copy: bool, default=TrueIf False, try to avoid a copy and do inplace scaling instead.This is not guaranteed to always work inplace; e.g. if the data isnot a NumPy array or scipy.sparse CSR matrix, a copy may still bereturned.",True
,"with_mean with_mean: bool, default=TrueIf True, center the data before scaling.This does not work (and will raise an exception) when attempted onsparse matrices, because centering them entails building a densematrix which in common use cases is likely to be too large to fit inmemory.",True
,"with_std with_std: bool, default=TrueIf True, scale the data to unit variance (or equivalently,unit standard deviation).",True
,"sparse_output sparse_output: bool, default=TrueWhen ``True``, it returns a SciPy sparse matrix/arrayin ""Compressed Sparse Row"" (CSR) format... versionadded:: 1.2 `sparse` was renamed to `sparse_output`",False
,"handle_unknown handle_unknown: {'error', 'ignore', 'infrequent_if_exist', 'warn'}, default='error'Specifies the way unknown categories are handled during :meth:`transform`.- 'error' : Raise an error if an unknown category is present during transform.- 'ignore' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will be all zeros. In the inverse transform, an unknown category will be denoted as None.- 'infrequent_if_exist' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will map to the infrequent category if it exists. The infrequent category will be mapped to the last position in the encoding. During inverse transform, an unknown category will be mapped to the category denoted `'infrequent'` if it exists. If the `'infrequent'` category does not exist, then :meth:`transform` and :meth:`inverse_transform` will handle an unknown category as with `handle_unknown='ignore'`. Infrequent categories exist based on `min_frequency` and `max_categories`. Read more in the :ref:`User Guide <encoder_infrequent_categories>`.- 'warn' : When an unknown category is encountered during transform a warning is issued, and the encoding then proceeds as described for `handle_unknown=""infrequent_if_exist""`... versionchanged:: 1.1 `'infrequent_if_exist'` was added to automatically handle unknown categories and infrequent categories... versionadded:: 1.6 The option `""warn""` was added in 1.6.",'ignore'
,"categories categories: 'auto' or a list of array-like, default='auto'Categories (unique values) per feature:- 'auto' : Determine categories automatically from the training data.- list : ``categories[i]`` holds the categories expected in the ith column. The passed categories should not mix strings and numeric values within a single feature, and should be sorted in case of numeric values.The used categories can be found in the ``categories_`` attribute... versionadded:: 0.20",'auto'
,"drop drop: {'first', 'if_binary'} or an array-like of shape (n_features,), default=NoneSpecifies a methodology to use to drop one of the categories perfeature. This is useful in situations where perfectly collinearfeatures cause problems, such as when feeding the resulting datainto an unregularized linear regression model.However, dropping one category breaks the symmetry of the originalrepresentation and can therefore induce a bias in downstream models,for instance for penalized linear classification or regression models.- None : retain all features (the default).- 'first' : drop the first category in each feature. If only one category is present, the feature will be dropped entirely.- 'if_binary' : drop the first category in each feature with two categories. Features with 1 or more than 2 categories are left intact.- array : ``drop[i]`` is the category in feature ``X[:, i]`` that should be dropped.When `max_categories` or `min_frequency` is configured to groupinfrequent categories, the dropping behavior is handled after thegrouping... versionadded:: 0.21 The parameter `drop` was added in 0.21... versionchanged:: 0.23 The option `drop='if_binary'` was added in 0.23... versionchanged:: 1.1 Support for dropping infrequent categories.",None
,"dtype dtype: number type, default=np.float64Desired dtype of output.",<class 'numpy.float64'>
,"min_frequency min_frequency: int or float, default=NoneSpecifies the minimum frequency below which a category will beconsidered infrequent.- If `int`, categories with a smaller cardinality will be considered infrequent.- If `float`, categories with a smaller cardinality than `min_frequency * n_samples` will be considered infrequent... versionadded:: 1.1 Read more in the :ref:`User Guide <encoder_infrequent_categories>`.",None
,"max_categories max_categories: int, default=NoneSpecifies an upper limit to the number of output features for each inputfeature when considering infrequent categories. If there are infrequentcategories, `max_categories` includes the category representing theinfrequent categories along with the frequent categories. If `None`,there is no limit to the number of output features... versionadded:: 1.1 Read more in the :ref:`User Guide <encoder_infrequent_categories>`.",None
,"feature_name_combiner feature_name_combiner: ""concat"" or callable, default=""concat""Callable with signature `def callable(input_feature, category)` that returns astring. This is used to create feature names to be returned by:meth:`get_feature_names_out`.`""concat""` concatenates encoded feature name and category with`feature + ""_"" + str(category)`.E.g. feature X with values 1, 6, 7 createfeature names `X_1, X_6, X_7`... versionadded:: 1.3",'concat'